### PR TITLE
Update gulp spawn to work with latest jekyll and bundle

### PR DESCRIPTION
**Pull request by jd4no**
I was trying to use this and could not get the build process to spawn. I believe its because the jekyll command required the bundler as well. I updated the build command in the gulp file to use the bundler to call jekyll.

### CODE REVIEW

**Comment by jd4no** [comment]
I actually went ahead and expanded the gulp file to handle different levels of work. I added npm scripts to run the browsersync server, build the site with dev settings, or build the site for production.

Dev settings adds sourcemaps for css.

Production settings purges, autoprefixes, and compresses css.

There are a significant amount of changes to the gulpfile, but ultimately it makes for a much faster development experience.

**Comment by taylorbryant** [comment]
This is so awesome! Thank you so much! I'm going to review this ASAP.

**Comment by jd4no** [comment]
Cheers. I’m still messing with the gulp file some.   
  
I keep having an issue with the Browsersync freezing on Reloading browsers. Seems like a somewhat common issue from what I’ve found so far.   Is that something you run into?   
  
 I think it has to do with the timing of which gulp tasks run causing a rebuild before other gulp tasks finish.   
  
  
  
 Joey Defourneaux     
  

  
  
>

**Comment by taylorbryant** [comment]
@allcontributors add @jd4no for code

**Pull request merged**
